name: Build

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  id-token: write
  attestations: write


jobs:
  website:
    name: Build Next.JS App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build 2>&1 | tee -a build.log
        env:
          STANDALONE: "1"

          DATABASE_URL: "file:db.db"
          EMAIL_AUTH_TOKEN: "no"
          S3_KEY_ID: "no"
          NEXT_PUBLIC_APP_URL: "https://emailthing.xyz"
          WEB_NOTIFICATIONS_PRIVATE_KEY: "no"
          NEXT_PUBLIC_NOTIFICATIONS_PUBLIC_KEY: "no"
          S3_URL: "no"
          S3_SECRET_ACCESS_KEY: "no"
      
      - name: Copy static asset files
        run: |
          mkdir --parents ./.next/standalone/public/_next/static 
          cp ./public -r ./.next/standalone
          cp ./.next/static -r ./.next/standalone/public/_next

      - name: Echo build log to $GITHUB_STEP_SUMMARY
        run: |
          echo "\`\`\`txt" >> $GITHUB_STEP_SUMMARY
          cat build.log >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          path: .next/standalone
          name: Standalone Next.js
          compression-level: 1

      - run: zip -r .next/standalone.zip .next/standalone

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: .next/standalone.zip
          subject-name: EmailThing - Standalone Next.js
